Fix failing emulator jobs for Dagger's GitHub Actions.
Looks like these emulator tests are failing because they rely on `SdkManagerCli` which requires JDK 18.

```
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
  	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
RELNOTES=N/A
PiperOrigin-RevId: 668257191